spring:
  application:
    name: bookstore-book-center
  datasource: 
    book-center: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true
      name: freezwsc
      url: jdbc:mysql://localhost:3306/freezwsc?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 'pass123'
      initial-size: 8
      max-active: 50
      min-idle: 8
      max-wait: 8000
      test-while-idle: true
      validation-query: 'select 1 from dual'
      connect-timeout: 1500
  
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    
feign:
  compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      
from: dev-environment-1.0...
