spring:
  application:
    name: bookstore-book-center
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    
#feign:
#  compression:
#    request:
#      enabled: true
#      mime-type: text/html,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
      
from: dev-environment-1.0...
